---
services:
  nginx:
    image: docker.io/library/fabiocicerchia/nginx-lua:1.28.0-alpine3.22.2
    container_name: nginx-lua
    docker pull 
    ports:
      - 2280:80
      - 22443:443
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data:/usr/share/nginx/html:ro
    labels:
      - traefik.enable=true
      - traefik.http.services.nginx.loadbalancer.server.port=80
      - traefik.http.routers.nginx.entrypoints=websecure
      - traefik.http.routers.nginx.rule=Host(`h2d2.freeboxos.fr`)
      - traefik.http.routers.nginx.tls=true
      - traefik.http.routers.nginx.tls.certresolver=cloudflare
      - traefik.http.routers.nginx.service=nginx
    networks:
      - frontend
    restart: unless-stopped

networks:
  frontend:
    external: true
