FROM jc21/nginx-proxy-manager:latest

# Install dependencies
USER root
RUN apt update && \
    apt install --no-cache nginx-plus-module-subs-filter

# Verify modules are loaded
RUN nginx -V 2>&1 | grep -- '--with-http_sub_module'

# Return to the default user
USER nginx