FROM jc21/nginx-proxy-manager:latest

# Install dependencies
USER root
RUN apk update && \
    apk add --no-cache nginx-mod-http-sub

# Verify modules are loaded
RUN nginx -V 2>&1 | grep -- '--with-http_sub_module'

# Return to the default user
USER nginx