version: '3.8'

services:
  brainswich:
    build: .
    ports:
      - "${BRAIN_PORT}:4999"
    volumes:
      - .:/app
      - ./src:/app/src
    working_dir: /app
    environment:
      - BRAIN_HOST=${BRAIN_HOST}
      - BRAIN_MAC=${BRAIN_MAC}
      - BRAIN_USER=${BRAIN_USER}
      - BRAIN_PSW=${BRAIN_PSW}
    restart: unless-stopped
