version: '3.8'

services:
  brainswitch:
    build: .
    ports:
      - "${BRAIN_PORT}:4999"
    # volumes:
    #   - ./src:/app/
    working_dir: /app
    environment:
      - BRAIN_HOST=${BRAIN_HOST}
      - BRAIN_MAC=${BRAIN_MAC}
      - BRAIN_USER=${BRAIN_USER}
      - BRAIN_PSW=${BRAIN_PSW}
      - PYTHONPATH=/app/
    network_mode: host # needed for wol
    restart: unless-stopped
