version: '3.8'

services:
  brainswich:
    build: .
    # container_name: brainswitch
    ports:
      - "4999:4999"
    volumes:
      - .:/app
    restart: unless-stopped
    environment:
      - BRAIN_HOST=${BRAIN_HOST}
      - BRAIN_MAC=${BRAIN_MAC}
      - BRAIN_USER=${BRAIN_USER}
      - BRAIN_PSW=${BRAIN_PSW}