# based on https://github.com/bubuntux/nordlynx?tab=readme-ov-file
networks:
    vpn_network:

services:
  
  vpn:
    image: ghcr.io/bubuntux/nordlynx
    container_name: NordLynxVPN
    cap_add:
      - NET_ADMIN
      # - NET_RAW
      
    environment:
      - PRIVATE_KEY=${NORDLYNX_TK}
      - NETWORK=192.168.1.0/24
      - COUNTRY_CODE=IT

    ports:
      - 8080:8080 # qbittorent webui
      - 6881:6881 # qbittorrent torrent port
      # - 9117:9117 #jackett
      - 8989:8989 #sonarr
      # - 7878:7878 #radarr
      # - 8686:8686 #lidarr
      # - 9696:9696 #prowlarr
    networks:
      - vpn_network

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /../config:/config
      - /../Media/TV:/tv
      - /../torrents:/downloads
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      - vpn

# Healthcheck was added to work with deunhealth to restart container
# on unhealthy status. labels allows deunhealth to monitor.
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    labels:
      - deunhealth.restart.on.unhealthy=true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /docker/qbittorrent:/config
      - /data:/data
    depends_on:
      - vpn
    network_mode: service:vpn
    healthcheck:
        test: ping -c 1 www.google.com || exit 1
        interval: 60s
        retries: 3
        start_period: 20s
        timeout: 10s

  # firefox:
  #     image: lscr.io/linuxserver/firefox:latest
  #     # hostname: firefox                        # won't work when you do network_mode
  #     container_name: firefox
  #     restart: unless-stopped
  #     depends_on:
  #         - vpn
  #     network_mode: service:vpn
  #     # ports:                                   # won't work; you need to do this in the nordlynx VPN container 
  #     #     - "3000:3000"                        # won't work; you need to do this in the nordlynx VPN container  
  #     #     - "3001:3001"                        # won't work; you need to do this in the nordlynx VPN container
  #     volumes:
  #         - /docker/mozilla/config:/config
  #     environment:
  #         - PUID=1000
  #         - PGID=1000
  #         - TZ=America/New_York
  #     security_opt:
  #         - seccomp:unconfined
  #     # shm_size: "1gb"
