version: "3"
services:
  nordvpn:
    image: ghcr.io/bubuntux/nordvpn
    container_name: nordvpn
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:              
      - USER=${NORDVPN_USER}
      - "PASS=${NORDVPN_PASS}"
      - CONNECT=France
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.1.0/24
    ports:
      #Torrent
     - 5050:5050 #Ceci est un exemple
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1